name = "worker-links"
type = "javascript"

# Change these!!
account_id = "ece1d09b06af2ced51407c97505ea0cc"
zone_id = "f0af03c025f4c50c50e71ed4e08dd754"
kv_namespaces = [  { binding = "kv", id = "1be44406edc142a084435e24dbf8ae1d", preview_id = "15cfb90ecd654b8f8a9ccd600832093f" }]

compatibility_flags = []
compatibility_date = "2021-11-13"

# Remove or comment out the route line if using workers_dev
workers_dev = false
route = "erisa.link/*"
